### PR TITLE
CI: Add Julia 1.10 (the current LTS) to the CI matrix; also, drop support for 1.6

### PR DESCRIPTION
**Pull request by DilumAluthge**
Before this PR, CI runs on the following Julia versions:
- 1.6 (previous LTS)
- nightly

After this PR, CI runs on the following Julia versions:
- 1.6 (previous LTS)
- 1.10 (current LTS)
- nightly

### CODE REVIEW

**Comment by DilumAluthge** [comment]
CI is failing on Windows (on all Julia versions). This is a known issue (#107).

CI is failing on Julia 1.6 (on all operating systems). This is a known issue (#110).

CI is passing on the following:
1. Julia 1.10 on Ubuntu and macOS.
2. Julia nightly on Ubuntu and macOS.

I would suggest that we merge this PR, and track the above failures in the linked issues.

**Comment by ericphanson** [comment]
I would be fine with dropping 1.6 support

**Comment by DilumAluthge** [comment]
> I would be fine with dropping 1.6 support

I have removed Julia 1.6 from the CI matrix in this PR.

**Review by ericphanson — APPROVED** [review]

**Comment by giordano** [comment]
Should also formally change the minimum required version https://github.com/JuliaEcosystem/PackageAnalyzer.jl/blob/fbdbd0bdf8e45d8834cf180b8e9d3afc4f2d4822/Project.toml#L34?  I'm not a fan of claiming to support a version but not actually test it on CI

**Comment by DilumAluthge** [comment]
Done in https://github.com/JuliaEcosystem/PackageAnalyzer.jl/pull/109/commits/cac7376346ec0868db6324b2924c9c38bc558cca

**Pull request merged**
